### PR TITLE
More Pets (Cow, PolarBear, Sheep)

### PR DESCRIPTION
**Pull request by GoodLucky777**
Add more pets. (Cow, PolarBear, Sheep)

### CODE REVIEW

**Comment by PetteriM1** [comment]
1. This does not compile
2. Please make it possible to feed polar bears so they are not too useless

**Comment by GoodLucky777** [comment]
> 1. This does not compile
> 2. Please make it possible to feed polar bears so they are not too useless

1. Fixed
2. What does Polar Bear eat?

**Comment by PetteriM1** [comment]
> > 1. This does not compile
> > 2. Please make it possible to feed polar bears so they are not too useless
> 
> 1. Fixed
> 2. What does Polar Bear eat?

Fish?

**Comment by GoodLucky777** [comment]
> > > 1. This does not compile
> > > 2. Please make it possible to feed polar bears so they are not too useless
> > 
> > 
> > 
> > 1. Fixed
> > 2. What does Polar Bear eat?
> 
> Fish?

I put them.

**Comment by PetteriM1** [comment]
Still doesn't compile

**Comment by GoodLucky777** [comment]
> Still doesn't compile

I forgot to import things. It is fixed.

**Pull request merged**
